name: CI/CD Dev Build Deployment
on:
  push:
    branches:
      - dev/**
      - lts/**
  workflow_dispatch:

jobs:
  pgwbuild:
    name: Pengwin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper bats
      - name: Build Debian Package
        run: |
          git clone https://github.com/wslutilities/wslu-debian builder
          cd builder/
          bash ./build.sh --ci dev pengwin
          cd ../
          mkdir -p ./pkgs
          mv ../wsl*.* ./pkgs
      - uses: actions/upload-artifact@v4
        with:
          name: PengwinDEBs
          path: pkgs
  pgwspdeploy:
    name: Pengwin Deploying
    needs: pgwbuild
    runs-on: ubuntu-22.04
    container: cimg/ruby:2.7
    steps:
      - name: Retrive package for deployment
        uses: actions/download-artifact@v4
        with:
          name: PengwinDEBs
          path: PengwinDEBs
      - run: gem install package_cloud
      - name: deploy to the dev
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PGW_DEV_DEPLOY_KEY }}
        run: package_cloud push --verbose whitewaterfoundry/wslu-dev/debian/bookworm ./PengwinDEBs/*.deb
  rpmcoprbuild:
    name: RPM Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq build-essential tar
      - name: configure
        run: |
          bash ./configure.sh --rpm copr
          cp extras/build/rpm/copr/wslu.spec ../wslu.spec
          rm -rf *
          mkdir -p SOURCES
          mkdir -p SPECS
          cp ../wslu-*.tar.gz SOURCES
          cp ../wslu.spec SPECS
      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
      - name: moving files
        run: |
          mkdir compiled_rpms
          cp SRPMS/* compiled_rpms
          cp RPMS/noarch/* compiled_rpms
      - uses: actions/upload-artifact@v4
        with:
          name: COPRRPMs
          path: compiled_rpms
  rpmdeploy:
    name: RPM Deploy
    needs: rpmcoprbuild
    runs-on: ubuntu-22.04
    container: cimg/ruby:2.7
    steps:
      - name: Retrive package for deployment
        uses: actions/download-artifact@v4
        with:
          name: COPRRPMs
          path: COPRRPMs
      - run: gem install package_cloud
      - name: deploy to the dev
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PGW_DEV_DEPLOY_KEY }}
        run: package_cloud push --verbose whitewaterfoundry/wslu-dev/fedora/42 ./COPRRPMs/*.rpm
