name: Package Deployment
on:
  push:
    tags:
      - v4.*
      - v3.*
  workflow_dispatch:
jobs:
  #tests:
    #uses: ./.github/workflows/tests.yaml
  pgwbuild:
    name: Pengwin
    runs-on: ubuntu-22.04
    #needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper bats wget
      - name: Build Debian Package
        run: |
          git clone https://github.com/wslutilities/wslu-debian builder
          cd ./builder
          bash ./build.sh latest pengwin
      - uses: actions/upload-artifact@v4
        with:
          name: PengwinDEBs
          path: builder/pkgs
  pgwspdeploy:
    name: Pengwin Deploying
    needs: pgwbuild
    runs-on: ubuntu-22.04
    container: cimg/ruby:2.7
    steps:
      - name: Retrive package for deployment
        uses: actions/download-artifact@v4
        with:
          name: PengwinDEBs
          path: PengwinDEBs
      - run: gem install package_cloud
      - name: deploy to bookworm 
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PGW_DEV_DEPLOY_KEY }}
        run: package_cloud push whitewaterfoundry/wslu/debian/bookworm ./PengwinDEBs/*.deb
  rpmcoprbuild:
    name: RPM Build
    #needs: tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq build-essential tar
      - name: configure
        run: |
          bash ./configure.sh --rpm copr
          cp extras/build/rpm/copr/wslu.spec ../wslu.spec
          rm -rf *
          mkdir -p SOURCES
          mkdir -p SPECS
          cp ../wslu-*.tar.gz SOURCES
          cp ../wslu.spec SPECS
      - name: rpmbuild
        uses: ./.github/actions/rpmbuild/
      - name: moving files
        run: |
          mkdir compiled_rpms
          cp SRPMS/* compiled_rpms
          cp RPMS/noarch/* compiled_rpms
      - uses: actions/upload-artifact@v4
        with:
          name: COPRRPMs
          path: compiled_rpms
  rpmdeploy:
    name: RPM Deploy
    needs: rpmcoprbuild
    runs-on: ubuntu-22.04
    container: cimg/ruby:2.7
    steps:
      - name: Retrive package for deployment
        uses: actions/download-artifact@v4
        with:
          name: COPRRPMs
          path: COPRRPMs
      - run: gem install package_cloud
      - name: deploy to the dev
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PGW_DEV_DEPLOY_KEY }}
        run: |
          package_cloud push --verbose whitewaterfoundry/wslu/fedora/40 ./COPRRPMs/*.rpm
          package_cloud push --verbose whitewaterfoundry/wslu/fedora/41 ./COPRRPMs/*.rpm
          package_cloud push --verbose whitewaterfoundry/wslu/fedora/42 ./COPRRPMs/*.rpm
          package_cloud push --verbose whitewaterfoundry/wslu/el/7 ./COPRRPMs/*.rpm
          package_cloud push --verbose whitewaterfoundry/wslu/el/8 ./COPRRPMs/*.rpm
          package_cloud push --verbose whitewaterfoundry/wslu/el/9 ./COPRRPMs/*.rpm
        
